name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Go application
        run: |
          cd ./go_app
          go mod tidy
          go build -o go_app
          ls -l go_app # ビルド結果を確認

      - name: Verify build output
        run: |
          if [ ! -f ./go_app/go_app ]; then
            echo "Build output not found!"
            exit 1
          fi

      # .env.productionの内容は、secretsに登録しておく ENV_PRODUCTION
      - name: Create .env (production)
        env:
          ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}
        run: |
          echo "$ENV_PRODUCTION" > go_app/.env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # デプロイ先ディレクトリの作成
            mkdir -p /var/www/google-map-app
            # 古いアプリを削除して新しいバイナリをアップロード
            rm -f /var/www/google-map-app/go_app
            # ホストキーをknown_hostsに追加
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true
            # ファイルをコピー
            scp ./go_app/go_app ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/google-map-app/
            # サービス再起動
            sudo systemctl restart go_app.service
