name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Go application
        run: |
          cd ./go_app
          go mod tidy
          go build -o go_app

      # .env.productionの内容は、secretsに登録しておく ENV_PRODUCTION
      - name: Create .env (production)
        env:
          ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}
        run: |
          echo "$ENV_PRODUCTION" > go_app/.env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # デプロイ先ディレクトリの作成
            mkdir -p /var/www/google-map-app
            # 古いアプリを削除して新しいバイナリをアップロード
            rm -f /var/www/google-map-app/go_app
            scp go_app ec2-user@${{ secrets.EC2_HOST }}:/var/www/google-map-app/
            # サービス再起動
            sudo systemctl start go_app.service

